/* ============================================================
   Aberdeen Pursuit Intelligence — signal corpus
   Extracted from the 13 public documents in hack-team-10/client-data/.
   Every signal carries evidence, a source reference and a provenance tag.
   Nothing here is invented; coverage gaps are stated on the account.
   ============================================================ */

const SIGNALS = [

  /* ---------------- ALPHABET ---------------- */
  {
    accountId: "alphabet",
    company: "Alphabet Inc.",
    docFile: "2026q2-alphabet-earnings-release.pdf",
    docType: "earnings release",
    period: "Q2 2026 (quarter ended June 30, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Revenue", value: "$119.8B", delta: "+24% YoY", sentiment: "up" },
      { label: "Google Cloud", value: "$24.8B", delta: "+82% YoY", sentiment: "up" },
      { label: "Operating income", value: "$40.8B", delta: "+30% YoY · margin 34%", sentiment: "up" },
      { label: "Q2 capex", value: "$44.9B", delta: "+100% YoY", sentiment: "up" },
      { label: "Q2 free cash flow", value: "-$5.9B", delta: "vs +$24.6B in Q4 2025", sentiment: "down" },
    ],
    managementQuote: "Our AI investments are redefining what's possible across every part of our business. Q2 was an amazing quarter, with Alphabet revenues growing 24% year-over-year and Google Cloud revenues accelerating to 82% growth, driven by demand for AI infrastructure and AI solutions. — Sundar Pichai, CEO",
    signals: [
      { headline: "Capex surge for AI infrastructure turns free cash flow negative",
        evidence: "Q2 purchases of property and equipment doubled YoY to $44.9B ($80.6B YTD), driving Q2 free cash flow to negative $5.9B.",
        quote: null, sourceRef: "pp. 7, 9 (cash flow; FCF reconciliation)", provenance: "press release",
        category: "technology-investment", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "A capex program of this scale creates urgent need for technology cost governance and infrastructure investment ROI tracking." },
      { headline: "$70B capital raise earmarked for AI infrastructure scaling",
        evidence: "June 2026: $49.6B net raised via common and mandatory convertible preferred stock, plus $20.3B of senior notes and a $40B ATM program.",
        quote: "aggregate net proceeds of $49.6 billion... including capital expenditures to scale AI infrastructure and global compute",
        sourceRef: "p. 2 (Equity Capital Raise)", provenance: "press release",
        category: "capital-allocation", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "Capital raised specifically to fund a massive multi-year infrastructure build-out signals mega-program delivery and assurance needs." },
      { headline: "Google Cloud accelerates 82% on enterprise AI demand",
        evidence: "Cloud revenue rose 82% YoY to $24.8B with segment operating income tripling to $8.8B; nearly 90% of the Fortune 100 use Gemini Enterprise.",
        quote: "Google Cloud saw a meaningful acceleration in growth as revenues increased 82% to $24.8 billion",
        sourceRef: "pp. 1, 8 (highlights; segment results)", provenance: "press release",
        category: "data-AI", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "Explosive enterprise AI platform adoption signals ecosystem-wide AI transformation work." },
      { headline: "$33.7B in YTD acquisitions",
        evidence: "Acquisitions net of cash totaled $33.7B YTD 2026 (vs $353M in H1 2025); goodwill grew from $33.4B to $57.8B since December 2025.",
        quote: null, sourceRef: "pp. 5, 7 (balance sheet; investing)", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "~$34B of acquisition spend in six months implies significant post-merger technology and operations integration workstreams." },
      { headline: "R&D and shared AI research spend escalating sharply",
        evidence: "Q2 R&D rose 32% YoY to $18.2B; unallocated Alphabet-level shared AI R&D grew 72% YoY to $5.8B.",
        quote: null, sourceRef: "pp. 2, 6, 8", provenance: "press release",
        category: "technology-investment", offering: "Technology Strategy & Operations",
        whyItMaps: "Rapidly scaling central AI R&D cost pools require operating-model and portfolio-prioritization discipline." },
    ],
    headwinds: ["Q2 FCF negative at -$5.9B on capex acceleration", "Other Bets loss widened to $1.8B", "Interest expense up to $1.28B as long-term debt hits $98.2B"],
    notes: "Headline net income is heavily distorted by a $98.0B one-time unrealized gain on equity securities. First-ever mandatory convertible preferred issuance underscores the scale of AI funding needs.",
  },

  /* ---------------- ARKEMA ---------------- */
  {
    accountId: "arkema",
    company: "Arkema",
    docFile: "arkema-press-release-results-q2-2026.pdf",
    docType: "press release + condensed interim financials",
    period: "Q2 2026 (published 30 July 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Sales", value: "€2,428M", delta: "+1.3% YoY (+3.2% organic)", sentiment: "up" },
      { label: "EBITDA", value: "€391M", delta: "+7.4% YoY · margin 16.1%", sentiment: "up" },
      { label: "Adjusted net income", value: "€129M", delta: "+7.8% YoY", sentiment: "up" },
      { label: "Recurring cash flow", value: "€78M", delta: "-29.3% YoY", sentiment: "down" },
      { label: "Net debt + hybrids", value: "€3,605M", delta: "2.9x EBITDA", sentiment: "flat" },
    ],
    managementQuote: "Our priorities will continue to combine strict discipline on costs and operational excellence with the ramp-up of our major projects, including the recent acquisition of Dow adhesives, our PA11 and Rilsan Clear plants in Singapore, the PVDF expansion in Calvert City... — Thierry Le Hénaff, Chairman & CEO",
    signals: [
      { headline: "Major capital projects ramping toward €50M incremental EBITDA",
        evidence: "Dow adhesives, PA11/Rilsan Clear Singapore, PVDF Calvert City, acrylics France and HF at Nutrien contributed ~€25M EBITDA in H1, expected ~€50M in 2026 vs 2025.",
        quote: "ramp up its major projects, which are expected to deliver around EUR 50 million additional EBITDA in 2026 versus 2025",
        sourceRef: "pp. 2, 5 (business performance; Outlook)", provenance: "press release",
        category: "growth-expansion", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A portfolio of simultaneous global plant ramp-ups with quantified EBITDA commitments needs program delivery assurance and benefits tracking." },
      { headline: "Dow adhesives acquisition entering integration phase",
        evidence: "The CEO names the 'recent acquisition of Dow adhesives' among major projects ramping in H2 2026, in a segment already delivering 30.5% of group sales.",
        quote: "the ramp-up of our major projects, including the recent acquisition of Dow adhesives",
        sourceRef: "pp. 1, 3 (CEO statement; Adhesive Solutions)", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "A recently closed carve-out from Dow creates classic integration needs — IT separation/integration, systems cutover, synergy realization." },
      { headline: "Organization streamlining and site reorganizations to offset fixed-cost inflation",
        evidence: "€46M of exceptional expenses in Q2, mainly reorganization of the Jarrie and Pierre-Bénite sites; full-year target of offsetting fixed cost inflation.",
        quote: "strict cost discipline and continued progress in streamlining the organization",
        sourceRef: "pp. 1–3", provenance: "press release",
        category: "restructuring", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Enterprise-wide streamlining extends to technology cost baselines, where IT financial management directly supports the savings agenda." },
      { headline: "Raw-material cost shock driving rapid repricing — a data/analytics problem",
        evidence: "The Middle East conflict triggered sharp raw-material inflation, forcing swift pricing adjustments: +5.1% group price effect, +16.0% in Primary Materials, while volumes fell 1.8%.",
        quote: "Sharp increase of raw material costs following the start of the conflict in the Middle East leading to swift pricing adjustments",
        sourceRef: "pp. 1–2, 5", provenance: "press release",
        category: "cost-pressure", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "Fast, granular pricing responses to volatile input costs depend on advanced pricing analytics — a natural extension of the live KM Copilot / Energy Management work." },
      { headline: "Growth concentrated in batteries, electronics, 3D printing, datacenter-linked markets",
        evidence: "Batteries, electronics and 3D printing sales grew ~15% YoY; Coating Solutions EBITDA jumped 52.9% to €78M.",
        quote: "A few pockets of growth continuing to contribute meaningfully, in particular batteries, electronics and 3D printing",
        sourceRef: "pp. 1–2, 4", provenance: "press release",
        category: "growth-expansion", offering: "Technology Strategy & Operations",
        whyItMaps: "Pivoting the portfolio toward high-growth advanced-technology end-markets requires technology and operations strategy behind the growth segments." },
      { headline: "Tight capital allocation — capex capped at €600M",
        evidence: "Q2 capex fell to €117M from €152M YoY; 2026 capex limited to €600M; net debt/EBITDA rose to 2.9x from 2.5x.",
        quote: "capital expenditure limited to EUR 600 million in 2026",
        sourceRef: "pp. 3, 5, 16", provenance: "press release",
        category: "capital-allocation", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Hard capex ceilings put every spend category, including IT, under value-for-money scrutiny." },
    ],
    headwinds: ["Middle East conflict: raw-material inflation and supply disruption", "Volumes down 1.8% YoY; weak Europe (France, Germany)", "€10M FX headwind on EBITDA", "Acrylic spreads at low levels in Asia since May"],
    notes: "Aberdeen is already inside: KM Copilot & Energy Management engagement at Clear Lake, in flight. Full 20-page package including interim financial statements.",
  },

  /* ---------------- CENTENE ---------------- */
  {
    accountId: "centene",
    company: "Centene Corporation",
    docFile: "CENTENE CORPORATION REPORTS SECOND QUARTER 2026 RESULTS - Jul 28, 2026.pdf",
    docType: "press release (web printout)",
    period: "Q2 2026 (reported July 28, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Total revenues", value: "$53.6B", delta: "+9.9% YoY", sentiment: "up" },
      { label: "Adjusted diluted EPS", value: "$2.51", delta: "vs $(0.16) in Q2 2025", sentiment: "up" },
      { label: "Health benefits ratio", value: "89.6%", delta: "improved from 93.0%", sentiment: "up" },
      { label: "At-risk membership", value: "25.9M", delta: "-7.6% YoY", sentiment: "down" },
    ],
    managementQuote: "Our second quarter results and improved full-year outlook represent meaningful milestones on our path to restoring profitability... focused on our goal of delivering industry-leading health outcomes with an industry-leading cost structure. — Sarah M. London, CEO",
    signals: [
      { headline: "Named enterprise optimization program with ~$100M of third-party vendor spend",
        evidence: "Q2 included $37M of enterprise optimization costs and $15M severance; FY2026 guidance excludes $355–405M of severance (incl. a voluntary separation program) and $85–115M of enterprise-optimization third-party vendor costs.",
        quote: "severance costs due to enterprise optimization and contract exits of approximately $355 million to $405 million, enterprise optimization third-party vendor costs of approximately $85 million to $115 million",
        sourceRef: "pp. 4–5 (non-GAAP reconciliation; guidance footnotes)", provenance: "press release",
        category: "restructuring", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "An active, named optimization program already buying ~$100M of external help is live demand for cost-structure and technology optimization advisory." },
      { headline: "Turnaround momentum drives $6B guidance raise",
        evidence: "FY26 revenue guidance raised $6.0B to $193.5–197.5B; swung from a $(253)M loss in Q2 2025 to $1,091M net earnings.",
        quote: "The Company is increasing total revenues guidance range by $6.0 billion",
        sourceRef: "p. 3 (Outlook)", provenance: "press release",
        category: "growth-expansion", offering: "Technology Strategy & Operations",
        whyItMaps: "A profitability turnaround anchored on an 'industry-leading cost structure' requires technology operating-model work to sustain the margin recovery." },
      { headline: "Medical cost trend management as the core execution lever",
        evidence: "Consolidated HBR improved 340bps to 89.6%; Medicaid HBR 93.9% 'reflecting continued execution in management of medical cost trend' across 25.9M members.",
        quote: "Medicaid HBR of 93.9%, in-line with expectations and reflecting continued execution in management of medical cost trend",
        sourceRef: "pp. 1–2", provenance: "press release",
        category: "data-AI", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "Managing medical cost trend at this scale is fundamentally a data, analytics, and predictive-modeling capability problem." },
      { headline: "Marketplace membership down 40% — per-member cost structures must shrink",
        evidence: "Marketplace membership fell 40% YoY to 3.49M; total at-risk membership dropped 2.1M; Commercial premium revenue declined 7% to $9.4B.",
        quote: null, sourceRef: "pp. 2, 11 (membership; supplemental)", provenance: "press release",
        category: "margin-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "A shrinking membership base forces right-sizing of per-member technology and administrative cost." },
      { headline: "Portfolio pruning via contract exits and divestitures",
        evidence: "H1 2026 includes a $10M gain on sale of a provider network, contract-exit severance, and $109M of medical claims liability removed via divestitures; workforce down to 59,800.",
        quote: null, sourceRef: "pp. 4–5, 11–12", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "Ongoing divestitures and contract exits require separation support, TSA management, and systems disentanglement." },
    ],
    headwinds: ["Marketplace membership -40% YoY", "Medical cost trend / utilization pressure", "Policy uncertainty: eAPTC renewal, CMS Stars, state rate adequacy", "$355–405M severance expected in FY26"],
    notes: "Browser printout of the IR page — carries cookie-banner text and truncated table columns at page edges. Former Aberdeen client, dormant in 2026 (win-back target).",
  },

  /* ---------------- CONSTELLATION ---------------- */
  {
    accountId: "constellation",
    company: "Constellation Energy Corporation",
    docFile: "Constellation Reports Second Quarter 2026 Results.pdf",
    docType: "earnings release (web printout)",
    period: "Q2 2026 (released Aug 6, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "GAAP net income", value: "$513M", delta: "-47% YoY", sentiment: "down" },
      { label: "Adjusted operating EPS", value: "$2.55", delta: "+34% YoY", sentiment: "up" },
      { label: "FY26 EPS guidance", value: "$11.50–12.50", delta: "raised", sentiment: "up" },
      { label: "Nuclear capacity factor", value: "93.0%", delta: "vs 94.8% Q2 2025", sentiment: "down" },
      { label: "New long-term PPAs", value: "920 MW", delta: "15–20 yr terms", sentiment: "up" },
    ],
    managementQuote: "We remain focused on integrating Calpine, capturing the value of our expanded fleet and investing in opportunities that generate attractive returns. — Shane Smith, EVP & CFO",
    signals: [
      { headline: "Calpine mega-merger integration in full swing",
        evidence: "Calpine acquired January 2026; Q2 shows $84M of merger/integration costs (up from $9M) plus $149M amortization of acquired commodity contracts; share count grew 314M → 360M.",
        quote: "We remain focused on integrating Calpine, capturing the value of our expanded fleet",
        sourceRef: "pp. 2, 6 (reconciliation)", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "A multi-billion-dollar merger mid-integration with rising costs is a direct trigger for post-merger integration and synergy-capture support." },
      { headline: "Crane Clean Energy Center nuclear restart advancing toward 2027",
        evidence: "FERC waiver granted to transfer Capacity Interconnection Rights from Eddystone to Crane; NRC approved Crane's fuel license amendment.",
        quote: "a major milestone moving us closer to restarting operations in 2027",
        sourceRef: "pp. 1–3 (Highlights; Recent Developments)", provenance: "press release",
        category: "growth-expansion", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A first-of-its-kind nuclear restart with hard regulatory milestones is a high-stakes program needing delivery assurance and schedule/risk governance." },
      { headline: "920 MW of new 15–20 year PPAs with corporate customers (incl. Walmart)",
        evidence: "Signed 920 MW of long-term PPAs with investment-grade customers starting 2029–2032, including a 176 MW Walmart agreement enabling a 30 MW Dresden expansion.",
        quote: "executing long-term agreements with our corporate customers",
        sourceRef: "pp. 1–3", provenance: "press release",
        category: "growth-expansion", offering: "Technology Strategy & Operations",
        whyItMaps: "Scaling a differentiated customer-facing commercial platform requires modernized commercial operations and contract management technology." },
      { headline: "$860M Brazos Valley divestiture closes out Calpine regulatory commitments",
        evidence: "Agreement with LS Power to divest the 606 MW Brazos Valley Energy Center for $860M — the last asset sale required under the Calpine deal; closing by year-end pending DOJ.",
        quote: "This marks the last asset sale required by our regulatory commitments under the acquisition.",
        sourceRef: "p. 3", provenance: "press release",
        category: "capital-allocation", offering: "M&A Enablement",
        whyItMaps: "A carve-out on a regulatory deadline needs separation planning, TSA management, and IT/data disentanglement." },
      { headline: "New fleet-wide operational metrics after portfolio transformation",
        evidence: "Post-Calpine, Constellation introduced Equivalent Forced Outage Factor as a new key metric for a 55 GW fleet powering the equivalent of 27 million homes.",
        quote: "we now consider Equivalent Forced Outage Factor (EFOF) to be a key operational metric beginning in 2026",
        sourceRef: "p. 4", provenance: "press release",
        category: "data-AI", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "Standing up new fleet-wide KPIs across a newly combined portfolio implies integrating operational data platforms and analytics across two legacy companies." },
    ],
    headwinds: ["86 planned refueling outage days vs 41 in Q2 2025", "GAAP EPS nearly halved on $340M unrealized fair-value losses", "Rising merger/integration cost drag"],
    notes: "\"Constellation\" appears both as a 2026 new account and in Aberdeen's past-engagement examples — identity must be confirmed against the CRM before outreach.",
  },

  /* ---------------- CORE NATURAL RESOURCES ---------------- */
  {
    accountId: "core",
    company: "Core Natural Resources, Inc.",
    docFile: "Core Natural Resources Reports Second Quarter 2026 Results - Aug 6, 2026.pdf",
    docType: "earnings release (web printout)",
    period: "Q2 2026 (released Aug 6, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Revenue", value: "$1.1B", delta: "roughly flat", sentiment: "flat" },
      { label: "Net income", value: "$126.5M", delta: "boosted by $125.4M insurance proceeds", sentiment: "up" },
      { label: "Adjusted EBITDA", value: "$323.6M", delta: "", sentiment: "up" },
      { label: "Free cash flow", value: "$148.0M", delta: "", sentiment: "up" },
      { label: "Liquidity", value: "$1.0B", delta: "incl. $474M cash", sentiment: "up" },
    ],
    managementQuote: "Looking ahead, we remain laser-focused on achieving world-class productivity and industry-leading cost performance across our entire mining portfolio. — Jimmy Brock, Chairman & CEO",
    signals: [
      { headline: "CONSOL–Arch merger integration still maturing",
        evidence: "Core was created Jan 2025 from the CONSOL/Arch merger; risk factors still flag integration and synergy-realization risk, and EBITDA remains adjusted for merger-related expenses.",
        quote: "the risk that the businesses of the company and Arch Resources, Inc. will not be integrated successfully",
        sourceRef: "pp. 6, 11–13", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "An 18-month-old merger of equals with flagged synergy risk is a prime candidate for integration management and synergy tracking." },
      { headline: "Aggressive per-ton cost reduction drive",
        evidence: "High-c.v. thermal cash cost/ton improved 9% QoQ to $38.58; metallurgical improved 7% to $85.65; management describes a 'step-change in operational execution'.",
        quote: "Drives significant per-ton cost and operating margin improvements",
        sourceRef: "pp. 1–3", provenance: "press release",
        category: "cost-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "A company-wide unit-cost agenda extends naturally to G&A and technology cost optimization." },
      { headline: "Recently announced CEO transition",
        evidence: "Forward-looking statements disclose 'risks related to the recently announced CEO transition' — a leadership change not discussed in the release body.",
        quote: "risks related to the recently announced CEO transition",
        sourceRef: "p. 13 (forward-looking statements)", provenance: "press release",
        category: "leadership-change", offering: "Technology Strategy & Operations",
        whyItMaps: "An incoming CEO typically triggers a strategy and operating-model refresh — a window for advisory entry." },
      { headline: "Rare earth elements / critical minerals ambition surfacing",
        evidence: "Risk factors reference uncertainties in Core's ability to 'mine, upgrade, process, and extract rare earth elements and critical minerals from its existing mines'.",
        quote: "the ability of Core to mine, upgrade, process, and extract rare earth elements and critical minerals",
        sourceRef: "p. 13", provenance: "press release",
        category: "growth-expansion", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "Standing up an entirely new extraction business line is a major capital program requiring business-case validation and delivery governance." },
      { headline: "Betting on AI-data-center-driven power demand",
        evidence: "Market update cites grid operators projecting demand growth 'spurred by reindustrialization and the AI-driven data center build-out'.",
        quote: "spurred by reindustrialization and the AI-driven data center build-out",
        sourceRef: "p. 3 (Market Update)", provenance: "press release",
        category: "growth-expansion", offering: "Technology Strategy & Operations",
        whyItMaps: "Positioning for AI-era load growth requires market analytics and demand-forecasting capability." },
    ],
    headwinds: ["Soft US thermal market: low gas prices, inflated stockpiles", "PRB negative cash margin -$0.57/ton", "Muted seaborne metallurgical markets", "Leer South combustion-related gas risk"],
    notes: "Q2 flattered by the $125.4M final Leer South insurance tranche. Most actionable signals (CEO transition, rare earths) appear only in forward-looking boilerplate. Roster match 'Core' is UNCONFIRMED.",
  },

  /* ---------------- CHESAPEAKE UTILITIES ---------------- */
  {
    accountId: "cpk",
    company: "Chesapeake Utilities Corporation",
    docFile: "CPK+Q2+2026+Earnings+Release.pdf",
    docType: "earnings release",
    period: "Q2 2026 (released Aug 6, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Operating revenues", value: "$201.9M", delta: "+4.7% YoY", sentiment: "up" },
      { label: "Net income", value: "$25.4M", delta: "+6.3% YoY", sentiment: "up" },
      { label: "YTD adjusted EPS", value: "$3.51", delta: "+8.0% YoY", sentiment: "up" },
      { label: "2026 capex guidance", value: "$550–600M", delta: "raised by $100M", sentiment: "up" },
    ],
    managementQuote: "Our second quarter results demonstrate consistent operational and financial performance as we make substantial progress on transforming for the next phase of sustained enterprise growth. — Jeff Householder, Chair, President & CEO",
    signals: [
      { headline: "Florida Energy Pathway: $1.2B flagship pipeline program launched",
        evidence: "Announced a $1.2B natural gas pipeline project in south Florida with ~250,000 Dts/d committed capacity and a 2030 in-service date; initial investments already in the raised 2026 capex guidance.",
        quote: "This represents a significant investment opportunity to bring capacity and reliability to south Florida",
        sourceRef: "pp. 1–2 (Highlights; guidance)", provenance: "press release",
        category: "growth-expansion", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A $1.2B multi-year megaproject — the company's largest — needs program governance and delivery assurance from day one." },
      { headline: "Five-year capital program stepped up beyond $2.2B",
        evidence: "2026 capex raised $100M to $550–600M; ~$1.4B invested through 2026 and >$2.2B expected for the five years ended 2028, above original $1.5–1.8B guidance.",
        quote: "The Company is increasing its 2026 capital expenditure guidance by $100 million",
        sourceRef: "p. 2", provenance: "press release",
        category: "capital-allocation", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A rapidly expanding multi-project capital portfolio raises portfolio-level delivery, prioritization and benefits-tracking needs." },
      { headline: "Florida City Gas integration winding down but still shaping results",
        evidence: "Adjusted EPS excludes FCG transition costs explicitly including 'transition services, consulting, system integration, rebranding'; the FCG rate case won interim rates of $16.2M annualized from July 2026.",
        quote: "transition services, consulting, system integration, rebranding, and legal fees",
        sourceRef: "pp. 1, 3", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "The FCG acquisition's system-integration workstream and follow-on rate case show live post-acquisition value-capture activity." },
      { headline: "Operating cost creep eroding margin gains",
        evidence: "YTD opex growth of $16.5M — payroll +$7.8M, D&A/property taxes +$5.0M, facilities/outside services +$3.7M, customer service +$2.7M — offsets about half the $30.3M YTD margin gain.",
        quote: null, sourceRef: "pp. 4–5 (variance tables)", provenance: "press release",
        category: "cost-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Rising service and outside-services costs against a regulated-returns model create a clear case for technology-enabled efficiency." },
      { headline: "Dense regulatory agenda across five jurisdictions",
        evidence: "Regulatory initiatives generated $31.0M of YTD adjusted gross margin (vs $18.2M prior year) across GUARD, SAFE, storm-protection and multiple rate cases.",
        quote: null, sourceRef: "pp. 1, 6", provenance: "press release",
        category: "regulatory", offering: "Technology Strategy & Operations",
        whyItMaps: "Managing simultaneous rate cases demands robust regulatory data, cost-allocation systems and reporting operations." },
    ],
    headwinds: ["CNG/RNG/LNG services margin declines", "Unfavorable customer consumption in Q2", "Rising interest charges and short-term borrowing", "EPS dilution from equity offerings"],
    notes: "Clean native PDF. No documented Aberdeen relationship — but Energy & Industrials is CoE priority sector #2, where credentials are thin.",
  },

  /* ---------------- DAUCH ---------------- */
  {
    accountId: "dauch",
    company: "Dauch Corporation",
    docFile: "Dauch Reports Second Quarter 2026 Financial Results.pdf",
    docType: "press release (PR Newswire capture)",
    period: "Q2 2026 (released Aug 7, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Sales", value: "$2.96B", delta: "+92% YoY", sentiment: "up" },
      { label: "Net income", value: "$1.0M", delta: "down from $39.3M", sentiment: "down" },
      { label: "Adjusted EBITDA", value: "$389.6M", delta: "+93% YoY · margin 13.2%", sentiment: "up" },
      { label: "Adjusted FCF", value: "$148.4M", delta: "+205% YoY", sentiment: "up" },
      { label: "Long-term debt", value: "$5.03B", delta: "up from $4.04B", sentiment: "down" },
    ],
    managementQuote: "The company's strong second-quarter results highlight the continued positive acceleration for the new Dauch Corporation. We are focused on unlocking the full strategic potential of the transformational acquisition we completed earlier in the year. — David C. Dauch, Chairman & CEO",
    signals: [
      { headline: "Transformational Dowlais acquisition — post-merger integration at scale",
        evidence: "The Feb 2026 combination with Dowlais (GKN Automotive, GKN Powder Metallurgy) nearly doubled sales to $2.96B; restructuring/acquisition costs hit $148.7M in H1; total assets jumped $6.7B → $11.05B.",
        quote: "We are focused on unlocking the full strategic potential of the transformational acquisition",
        sourceRef: "pp. 1, 7–8, 14", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "A company mid-flight on an acquisition that doubled its size needs integration management, systems consolidation, and Day-2 operating model support." },
      { headline: "Formal synergy program with raised targets — >$100M run rate by end of year one",
        evidence: "2026 outlook raised synergy benefits to $60–75M, targeting >$100M run rate, backed by $95–110M synergy implementation payments and $115–150M restructuring payments.",
        quote: "synergy benefits of $60 - $75 million... equating to a run rate of greater than $100 million by the end of year one",
        sourceRef: "pp. 2, 13 (outlook)", provenance: "press release",
        category: "restructuring", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A multi-hundred-million-dollar synergy program with public run-rate commitments needs program assurance to hit targets." },
      { headline: "Segment and footprint reorganization across 175+ locations",
        evidence: "Q1 2026 moved plants from Metal Forming to Driveline 'to better align our product and process technologies'; operations span 24 countries and 175+ locations.",
        quote: "to better align our product and process technologies",
        sourceRef: "pp. 4, 14", provenance: "press release",
        category: "restructuring", offering: "Technology Strategy & Operations",
        whyItMaps: "Re-segmenting a newly combined global manufacturer implies harmonizing operating models, ERP/reporting structures, and technology stacks." },
      { headline: "Elevated debt and interest burden post-acquisition",
        evidence: "Long-term debt at $5.03B; Q2 interest expense doubled YoY to $89.8M; FY outlook assumes $350M interest against a projected GAAP net loss of $135–200M.",
        quote: null, sourceRef: "pp. 7–8, 13", provenance: "press release",
        category: "cost-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Heavy leverage and a GAAP loss create urgent pressure to rationalize duplicated IT spend across the combined Dauch/Dowlais estate." },
      { headline: "AI-enhanced cyber threats and IT-systems risk called out explicitly",
        evidence: "Risk factors flag IT systems/cloud failure risk and 'increasingly sophisticated cyber attacks incorporating use of artificial intelligence' — mid-way through merging two global IT environments.",
        quote: "increasingly sophisticated cyber attacks incorporating use of artificial intelligence",
        sourceRef: "p. 5 (risk factors)", provenance: "press release",
        category: "technology-investment", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "Board-level acknowledgment of AI-driven cyber risk during a two-company IT integration signals demand for resilient technology and data architecture." },
    ],
    headwinds: ["Interest expense doubled to $89.8M on $5.0B debt", "FY26 GAAP net loss of $135–200M projected", "Tariff/USMCA exposure", "Chinese OEM competition; ICE-to-EV transition risk"],
    notes: "Dauch is the renamed American Axle & Manufacturing entity (contacts still use @aam.com). No Aberdeen relationship documented — cold, but the signal density is exceptional.",
  },

  /* ---------------- KRISPY KREME ---------------- */
  {
    accountId: "krispykreme",
    company: "Krispy Kreme, Inc.",
    docFile: "Krispy Kreme Reports Second Quarter 2026 Financial Results.pdf",
    docType: "press release (Business Wire capture)",
    period: "Q2 2026 (quarter ended June 28, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Net revenue", value: "$331.0M", delta: "-12.8% YoY", sentiment: "down" },
      { label: "GAAP net loss", value: "$(19.8)M", delta: "improved $421.3M YoY", sentiment: "up" },
      { label: "Adjusted EBITDA", value: "$28.8M", delta: "+43.2% YoY · margin 8.7% (+340bps)", sentiment: "up" },
      { label: "Net leverage", value: "5.4x", delta: "-1.3x vs Q4 2025", sentiment: "up" },
      { label: "Cash on hand", value: "$21.8M", delta: "$263.9M total liquidity", sentiment: "down" },
    ],
    managementQuote: "Our results demonstrate the success of the actions we are taking to grow the business and improve profitability, including a significant expansion in Adjusted EBITDA margin of 340 basis points. — Josh Charlesworth, CEO",
    signals: [
      { headline: "Four-part turnaround plan in active execution",
        evidence: "The August 2025 plan (refranchising, ROIC, margin expansion, sustainable growth) is delivering: capex down 70% in H1, EBITDA margin +340bps, $10.3M YTD of strategic-initiative costs.",
        quote: "The Company's comprehensive turnaround plan... is designed to deleverage the balance sheet and deliver sustainable, profitable growth.",
        sourceRef: "pp. 1–2, 16", provenance: "press release",
        category: "restructuring", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A publicly committed multi-workstream turnaround with quarterly-scrutinized milestones needs independent program assurance and change delivery capacity." },
      { headline: "Aggressive refranchising reshaping the operating model",
        evidence: "Japan and western-US JV refranchised in March 2026 for $111.4M net proceeds YTD; franchised share of systemwide sales jumped ~25% → ~42%, targeting ~50% by fiscal 2027.",
        quote: "the Company's goal remains to reach approximately 50% of systemwide sales generated by franchisees",
        sourceRef: "pp. 5–6, 14", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "Serial divestiture/refranchising deals require carve-out execution, TSAs, and systems separation — classic M&A enablement work." },
      { headline: "US logistics just outsourced to a third party",
        evidence: "Completed 3PL outsourcing April 2026; $4.2M YTD transition costs; US segment EBITDA margin rose ~370bps to 8.0%.",
        quote: "Completed outsourcing of U.S. logistics in April 2026.",
        sourceRef: "pp. 2, 18", provenance: "press release",
        category: "cost-pressure", offering: "Technology Strategy & Operations",
        whyItMaps: "A just-completed 3PL transition creates follow-on needs in supply-chain systems integration and vendor governance." },
      { headline: "Digital becoming a core growth engine",
        evidence: "Digital sales reached 19.8% of retail sales (+190bps YoY); US average revenue per door per week up 33.2% to ~$697; 448 fresh delivery doors added in H1.",
        quote: null, sourceRef: "pp. 2–3 (Key Operating Metrics)", provenance: "press release",
        category: "data-AI", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "A fast-growing digital/omnichannel business across 15,665 points of access needs modern data and channel analytics to sustain growth." },
      { headline: "Residual cybersecurity remediation history",
        evidence: "Prior-year costs included $5.3M (H1 2025) remediating the 2024 Cybersecurity Incident; IT failure and cyber risk remain lead risk factors.",
        quote: "costs related to remediation of the 2024 Cybersecurity Incident",
        sourceRef: "pp. 9, 19", provenance: "press release",
        category: "technology-investment", offering: "Technology Strategy & Operations",
        whyItMaps: "A recent material cyber incident plus ongoing IT-risk disclosure signals appetite for technology resilience investment." },
    ],
    headwinds: ["Revenue -12.8% on refranchising and ~2,400 door closures (ended McDonald's USA partnership)", "International organic revenue -5.1% (UK, Australia)", "Leverage 5.4x with only $21.8M cash", "Commodity, tariff, FX risks"],
    notes: "Former Aberdeen client, dormant in 2026 — the turnaround creates a concrete win-back opening. Prior-year comparison flattered by a $356M goodwill impairment in Q2 2025.",
  },

  /* ---------------- LPL FINANCIAL ---------------- */
  {
    accountId: "lpl",
    company: "LPL Financial Holdings Inc.",
    docFile: "lpl_financial_q2_2026_earnings_release.pdf",
    docType: "earnings release",
    period: "Q2 2026 (released July 30, 2026)",
    provenanceClass: "press release",
    keyFinancials: [
      { label: "Net income", value: "$379M", delta: "+39% YoY", sentiment: "up" },
      { label: "Adjusted EPS", value: "$5.84", delta: "+29% YoY (record)", sentiment: "up" },
      { label: "Total client assets", value: "$2.6T", delta: "+34% YoY", sentiment: "up" },
      { label: "Q2 capex", value: "$199.4M", delta: "+46% YoY", sentiment: "up" },
      { label: "Organic net new assets", value: "$23B", delta: "4% annualized", sentiment: "up" },
    ],
    managementQuote: "We remain focused on our strategic priorities, and are on track to onboard Commonwealth later this year. — Rich Steinmeier, CEO",
    signals: [
      { headline: "Commonwealth conversion — a massive Q4 2026 onboarding program",
        evidence: "Conversion on track for Q4 2026 with ~90% asset retention expected; estimated run-rate EBITDA raised from $410M to $435M; onboarding delay flagged as a top risk.",
        quote: "On track to complete the conversion in the fourth quarter of 2026... Estimated run-rate EBITDA has increased from $410 million to $435 million",
        sourceRef: "pp. 1, 3–4", provenance: "press release",
        category: "M&A", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A single-quarter conversion of an entire broker-dealer with a public 90% retention target is exactly the migration that demands program assurance." },
      { headline: "Serial acquirer cadence continues (Mariner, Liquidity & Succession)",
        evidence: "Closed Mariner Advisor Network (367 advisors, ~$31B client assets) and four Liquidity & Succession deals in Q2; acquisition costs ran $49.0M in the quarter.",
        quote: "Closed on the acquisition of Mariner Advisor Network... 367 advisors who collectively manage $31 billion",
        sourceRef: "pp. 1, 19", provenance: "press release",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "Continuous multi-deal M&A requires repeatable integration playbooks, diligence support, and synergy tracking." },
      { headline: "Technology capex accelerating +46% YoY",
        evidence: "Q2 capex hit $199.4M (vs $137.0M); occupancy/equipment expense +54% YoY; the firm provides 'fintech tools' to 32,475 advisors across ~1,100 institutions.",
        quote: null, sourceRef: "pp. 2, 5, 15", provenance: "press release",
        category: "technology-investment", offering: "Technology Strategy & Operations",
        whyItMaps: "Capex growing 46% to support a scaling advisor platform signals major in-flight technology build-out that benefits from operating-model guidance." },
      { headline: "Active cost discipline — Core G&A outlook lowered mid-acquisition",
        evidence: "2026 Core G&A outlook lowered to $2,140–2,165M; Core G&A fell 2% sequentially to $519M despite the M&A onboarding load.",
        quote: "record adjusted earnings per share and further progress driving improved operating leverage — Matt Audette, President & CFO",
        sourceRef: "pp. 1–2, 8", provenance: "press release",
        category: "cost-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "A public, lowered expense commitment while absorbing acquisitions creates demand for technology cost transparency and benchmarking." },
      { headline: "Third-party provider and IT/cyber/sourcing risk flagged",
        evidence: "Risk factors cite 'the performance of third-party service providers to which business processes have been transitioned' and IT, cyber and sourcing risks.",
        quote: "the Company's ability to control operating risks, information technology systems risks, cybersecurity risks and sourcing risks",
        sourceRef: "p. 4", provenance: "press release",
        category: "regulatory", offering: "Technology Strategy & Operations",
        whyItMaps: "Outsourced processes plus stated IT risk in a regulated wealth manager point to vendor governance and technology-risk operating models." },
    ],
    headwinds: ["Net interest income -40% YoY as rates fell", "Client cash % of assets declining", "Brokerage net new assets negative $(7.1)B", "Commonwealth execution risk concentrated in Q4 2026"],
    notes: "Roster client. Growth/integration-driven signals rather than distress-driven — Financial Services is CoE priority sector #1.",
  },

  /* ---------------- CORNERSTONE BUILDING BRANDS ---------------- */
  {
    accountId: "cornerstone",
    company: "Cornerstone Building Brands, Inc.",
    docFile: "Cornerstone report.pdf",
    docType: "SEC Form 10-Q (51 pages)",
    period: "Q1 FY2026 (three months ended April 4, 2026)",
    provenanceClass: "filing",
    keyFinancials: [
      { label: "Net sales", value: "$1,209.3M", delta: "+2.9% YoY", sentiment: "up" },
      { label: "Gross margin", value: "13.2%", delta: "down from 20.1%", sentiment: "down" },
      { label: "Net loss", value: "$(192.5)M", delta: "widened from $(110.6)M", sentiment: "down" },
      { label: "Adjusted EBITDA", value: "$1.1M", delta: "collapsed from $91.9M", sentiment: "down" },
      { label: "Total equity", value: "$(707.9)M", delta: "deficit", sentiment: "down" },
    ],
    managementQuote: "We continue to evaluate opportunities to mitigate the impact of tariffs... however, there can be no assurance that such efforts will be successful.",
    signals: [
      { headline: "ERP go-live failure created an SEC-disclosed material weakness",
        evidence: "Disclosure controls deemed not effective: the Metal Solutions ERP implementation failed because assigned team members lacked the knowledge to develop requirements, configure the system, and complete UAT before go-live. An outside firm was retained; new SDLC policy and governance implemented.",
        quote: "the assigned team members lacked the requisite knowledge and experience to develop functional requirements, configure the system, and complete user acceptance tests sufficient to fully test the enterprise resource planning system prior to going live",
        sourceRef: "Item 4, Controls and Procedures, pp. 30–31", provenance: "filing",
        category: "technology-investment", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A failed ERP go-live with SEC-disclosed material weakness and ongoing remediation is the single most direct trigger for independent program assurance in this corpus." },
      { headline: "Unintegrated 2024 acquisitions still lack effective IT controls",
        evidence: "A second material weakness persists: IT general controls and journal-entry controls never effectively implemented at Harvey Building Products and Mueller Supply (both acquired 2024).",
        quote: "The Company did not design, implement, and maintain effective information technology general controls... at Harvey Building Products Corp. and Mueller Supply Company, Inc.",
        sourceRef: "Item 4, p. 31", provenance: "filing",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "Post-merger IT/controls integration incomplete two years after close — classic M&A technology-integration enablement work." },
      { headline: "Metal Sales integration adds 21 facilities to a strained platform",
        evidence: "Metal Sales Manufacturing acquired Sept 2025 for ~$181.8M, adding ~900 employees at 21 US facilities to the same segment that just failed its ERP rollout.",
        quote: "Metal Sales had approximately 900 employees at 21 facilities across the United States",
        sourceRef: "Note 3; MD&A p. 23", provenance: "filing",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "A large in-flight integration into a segment with a live ERP material weakness needs integration planning and systems consolidation." },
      { headline: "Margin collapse from tariffs forcing cost action",
        evidence: "Gross margin fell 20.1% → 13.2%; Adjusted EBITDA fell $91.9M → $1.1M on steel/PVC/aluminum/glass inflation; Windows & Doors EBITDA swung to $(5.1)M from $42.4M.",
        quote: "These rapidly changing policies and dynamics pose a risk to our supply chain and cost structure.",
        sourceRef: "MD&A pp. 22–25", provenance: "filing",
        category: "margin-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Near-zero EBITDA with active cost-management mandates makes IT cost takeout an immediate, fundable priority." },
      { headline: "Interim CFO installed; executive retention program launched",
        evidence: "Christian Storch became Interim CFO Feb 6, 2026; base salary raised $500K → $700K in May; a form Executive Officer Retention Letter was filed.",
        quote: null, sourceRef: "Part II Item 5, p. 32; Exhibits 10.1–10.2", provenance: "filing",
        category: "leadership-change", offering: "Technology Strategy & Operations",
        whyItMaps: "An interim CFO stabilizing a distressed finance function is a natural buyer of external transformation support." },
    ],
    headwinds: ["$5.4B future debt payments; $125.9M quarterly interest; $(707.9)M equity deficit", "Tariff and commodity inflation compressing all segments", "Negative operating cash flow $(107.6)M", "Two unresolved material weaknesses in ICFR"],
    notes: "Privately held (CD&R) but SEC-reporting due to debt — a PE-sponsored distressed asset. NOT the same company as Aberdeen's former client 'Cornerstone Care'; records must stay separate.",
  },

  /* ---------------- NOVANT HEALTH ---------------- */
  {
    accountId: "novant",
    company: "Novant Health, Inc.",
    docFile: "novant-health-q1-2026-combined-group-pkg.pdf",
    docType: "quarterly financial & statistical report (municipal-bond continuing disclosure)",
    period: "Q1 2026 (three months ended March 31, 2026)",
    provenanceClass: "filing",
    keyFinancials: [
      { label: "Operating revenues", value: "$3,088.0M", delta: "+13.4% YoY", sentiment: "up" },
      { label: "Operating income", value: "$91.3M", delta: "margin 3.0%", sentiment: "up" },
      { label: "Salaries & benefits", value: "$1,522.1M", delta: "+12.9% YoY", sentiment: "down" },
      { label: "Capex", value: "$277.7M", delta: "+50% YoY", sentiment: "up" },
      { label: "Cash & equivalents", value: "$588.1M", delta: "down from $945.6M at year-end", sentiment: "down" },
    ],
    managementQuote: "Salaries and benefits increased $173,682, or 12.9%, compared to the same period for the prior year, primarily due to merit and market-based pay adjustments and acquisitions. (MD&A)",
    signals: [
      { headline: "Capex surge of +50% with major capital projects entering service",
        evidence: "Q1 capex of $277.7M vs $185.1M YoY; D&A rose 14.8% 'primarily due to capital projects placed in service and acquisitions' across a 19-medical-center, 900+ location network.",
        quote: "Capital expenditures were $277,742 for the three months ended March 31, 2026.",
        sourceRef: "MD&A p. 8; cash flows p. 3", provenance: "filing",
        category: "growth-expansion", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A rapidly expanding capital program across a multi-hospital system creates demand for program assurance, PMO and delivery governance." },
      { headline: "$839M energy monetization with a $172M four-year upgrade program",
        evidence: "Received $838.95M in June 2025 for a 30-year Energy Services Agreement; separately committed to a $172.0M energy-efficiency upgrade program over four years (up to $200M more elective), $102.6M advanced by March 31, 2026.",
        quote: "The total project cost is anticipated to be $172,000 [thousand], which is being advanced on a fixed schedule over four years.",
        sourceRef: "MD&A pp. 8–9 (Debt Structure)", provenance: "filing",
        category: "capital-allocation", offering: "Large Program Assurance, Delivery & Change",
        whyItMaps: "A multi-year, third-party-operated infrastructure program with staged funding needs independent delivery assurance and vendor governance." },
      { headline: "Labor inflation at 12.9% squeezing a 3.0% operating margin",
        evidence: "Salaries +$173.7M (+12.9%) YoY; other opex +$164.1M (+14.1%) on HASP assessments and supplies; operating activities used $66.5M of cash.",
        quote: "Other operating expenses increased $164,115, or 14.1%... primarily due to increases in expenses accrued for HASP assessments, inflation, increased medical supplies expense",
        sourceRef: "MD&A p. 7", provenance: "filing",
        category: "cost-pressure", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "Double-digit expense growth on thin margins makes technology cost transparency a compelling, quantifiable pitch." },
      { headline: "Growth-by-acquisition continues to reshape the system",
        evidence: "Revenue, salaries and D&A growth each partly attributed to acquisitions; network now includes recently added East Cooper, SC Coastal and Hilton Head medical centers.",
        quote: null, sourceRef: "MD&A p. 7; statistics p. 4", provenance: "filing",
        category: "M&A", offering: "M&A Enablement",
        whyItMaps: "Ongoing hospital acquisitions require systems integration, day-1/day-100 planning and synergy capture — where Aberdeen's healthcare M&A credentials are strongest." },
      { headline: "New treasury sophistication: CP program, repo, expanded revolver",
        evidence: "Established a $500M taxable commercial paper program ($350M outstanding), a securities repurchase program ($104.8M), and upsized the revolver $250M → $500M against $5,280.3M total long-term debt.",
        quote: "Under the program, the Company may issue Taxable Commercial Paper Notes up to $500,000 [thousand] in face value.",
        sourceRef: "Liquidity table p. 5; MD&A pp. 8–9", provenance: "filing",
        category: "capital-allocation", offering: "Technology Strategy & Operations",
        whyItMaps: "An increasingly complex capital structure funding growth signals appetite for technology-enabled finance and operating-model support." },
    ],
    headwinds: ["Investment income fell to $16.5M from $36.7M; cash down $357.5M in the quarter", "Operating activities used $66.5M cash on an AR build", "Wage inflation outpacing patient revenue growth", "Average daily census and ED visits both lower YoY"],
    notes: "Not-for-profit health system (NC/SC), figures in $ thousands. Representative healthcare roster client — squarely in Aberdeen's credential stronghold.",
  },

  /* ---------------- LIVESTOCK FEEDS ---------------- */
  {
    accountId: "lsf",
    company: "Livestock Feeds Plc",
    docFile: "LSF-UNAUDITED-FS-JUNE-2026.pdf",
    docType: "unaudited interim financial statements (IAS 34, Nigerian Exchange)",
    period: "H1 2026 (six months ended 30 June 2026) — figures in ₦'000",
    provenanceClass: "filing",
    keyFinancials: [
      { label: "Revenue", value: "₦14.82bn", delta: "-28.7% YoY", sentiment: "down" },
      { label: "Profit before tax", value: "₦1.33bn", delta: "up ~8.7x YoY", sentiment: "up" },
      { label: "Inventories", value: "₦11.28bn", delta: "+68% vs FY2025", sentiment: "down" },
      { label: "Gearing", value: "88%", delta: "vs sub-60% policy", sentiment: "down" },
    ],
    managementQuote: null,
    signals: [
      { headline: "Balance-sheet turnaround after a ₦3.0bn FY2025 loss",
        evidence: "H1 2026 delivered ₦1.14bn profit, rebuilding total equity to ₦1.53bn after FY2025 losses wiped equity to ₦387.7M.",
        quote: null, sourceRef: "Statement of Changes in Equity p. 4", provenance: "filing",
        category: "restructuring", offering: "Technology Strategy & Operations",
        whyItMaps: "A company mid-turnaround needs operating-model and performance-management support to lock in the recovery." },
      { headline: "Debt restructured through parent: ₦7.0bn commercial paper via UAC",
        evidence: "All bank borrowings (₦13.7bn in 2025) fully repaid by 30 June 2026; parent UAC of Nigeria sourced a ₦7.0bn 270-day CP maturing July 2026 as an intercompany loan.",
        quote: "As of 30th June 2026, there is no outstanding bank borrowing as all loans have been fully settled.",
        sourceRef: "Notes 28, 11, 29", provenance: "filing",
        category: "capital-allocation", offering: "IT Financial Mgmt. & Optimization",
        whyItMaps: "A parent-funded refinancing with a near-term CP maturity puts a premium on cost discipline and cash visibility." },
      { headline: "Rising technology and R&D spend on a small base (SAP)",
        evidence: "IT expense of ₦116.9M in admin costs; prepayments include SAP licence fees; R&D spend jumped 6x to ₦44.0M.",
        quote: "Others relates to SAP licence fee, internet services, generator maintenance and training etc",
        sourceRef: "Notes 8, 20", provenance: "filing",
        category: "technology-investment", offering: "Technology Future-Proofing (AI & Data)",
        whyItMaps: "An SAP-running manufacturer stepping up IT spend is a candidate for ERP value-optimization advisory — though geography rules this one out for Aberdeen." },
    ],
    headwinds: ["Naira currency risk and near-term ₦7.0bn CP maturity", "Working-capital squeeze: current liabilities exceed current assets", "Revenue -29% across all three regions"],
    notes: "Figures in Nigerian naira thousands, not USD. Subsidiary of UAC of Nigeria (73.29%). Outside Aberdeen's documented geographic footprint — deprioritized.",
  },

  /* ---------------- LOMA LINDA ---------------- */
  {
    accountId: "lomalinda",
    company: "Loma Linda University Health",
    docFile: "Loma Linda University Health july 2026 release.html",
    docType: "third-party market-news digest (Crescendo Interactive content on llulegacy.org)",
    period: "Published July 7, 2023 — NOT a 2026 document, NOT Loma Linda's financials",
    provenanceClass: "third-party digest",
    keyFinancials: [],
    managementQuote: null,
    signals: [],
    headwinds: [],
    notes: "Confirmed unusable: despite the filename, the file contains zero Loma Linda financial data. It is a saved donor-website news page covering Q2 2023 earnings of McCormick, Levi Strauss and Goodfellow, plus 2023 Treasury-yield commentary. No figures from this page may be attributed to Loma Linda. The account itself is real (2026 new client, healthcare roster) — the signal gap is a data-collection action item, not a reason to drop the account.",
  },
];
